Switch e2e module2 to use Sepolia
aws-samples/web3-workshop pull request #59
Opened 2024-08-09 00:25 UTC by ebaizel

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-08-11 18:00 UTC, dpdornseifer requested changes
PR looks good. Just a little cleanup required before we can merge

2024-08-11 18:00 UTC, dpdornseifer commented on tests/module2/deploy_smart_contract.sh
> +    # alchemy_goerli_api_key=$(aws ssm get-parameter --name "/web3/aa/goerli_api_key" --region ${CDK_DEPLOY_REGION} | jq -r ".Parameter.Value" )
commented out code no longer required in script

2024-08-12 17:29 UTC, ebaizel commented on tests/module2/deploy_smart_contract.sh
> +    # alchemy_goerli_api_key=$(aws ssm get-parameter --name "/web3/aa/goerli_api_key" --region ${CDK_DEPLOY_REGION} | jq -r ".Parameter.Value" )
Removed

2024-08-13 07:44 UTC, dpdornseifer approved these changes

2024-08-13 07:44 UTC, merged